- hosts: all
  become: yes

  tasks:
   - name: Install nginx
     apt: package=nginx state=latest update_cache=true
     notify:
      - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started



  tasks:
   - name: Hashicorp Consul
     url: https://www.consul.io/downloads
     dest: /home/ubuntu
     notify:
       - Hashicorp Consul
    
    
  handlers:
   -name: Hashicorp Consul
    service: name=Hashicrop state=started


    
  
