- hosts: all
  become: yes

  tasks:
   - name: Install nginx
     apt: package=nginx state=latest update_cache=true
     notify:
      - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
