- hosts: all
  become: yes

  tasks:
   - name: Install nginx
     apt: package=nginx state=latest update_cache=true
     notify:
      - start nginx

   - name: Hashicorp consul
     apt: package=consul state=latest update_cache=true
     notify:
       - start consul


   - name: Hashicorp nomad
     apt: package=nomad state=latest update_cache=true
     notify:
       - start nomad

  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: Hashicorp consul
      service: name=consul state=started
    - name: Hashicorp nomad
      service: name=nomad state=started

